In [5]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [6]:
PATH = "./data"
os.listdir(PATH)

['DigiDB_movelist.csv', 'DigiDB_supportlist.csv', 'DigiDB_digimonlist.csv']

In [7]:
movelist    = pd.read_csv(os.path.join(PATH,'DigiDB_movelist.csv'))
supportlist = pd.read_csv(os.path.join(PATH,'DigiDB_supportlist.csv'))
digimonlist = pd.read_csv(os.path.join(PATH,'DigiDB_digimonlist.csv'))

In [8]:
movelist.head()

,Move,SP Cost,Type,Power,Attribute,Inheritable,Description
0,Wolkenapalm I,3,Physical,65,Fire,Yes,"Physical attack, 65 Fire damage to one foe. 95..."
1,Wolkenapalm II,6,Physical,85,Fire,Yes,"Physical attack, 85 Fire damage to one foe. 95..."
2,Wolkenapalm III,9,Physical,105,Fire,Yes,"Physical attack, 105 Fire damage to one foe. 9..."
3,Burst Flame I,3,Magic,55,Fire,Yes,"Magic attack, 55 Fire damage to one foe. 95% a..."
4,Burst Flame II,6,Magic,75,Fire,Yes,"Magic attack, 75 Fire damage to one foe. 95% a..."

In [9]:
supportlist.head()

               Name                                        Description
0     Adroit Wisdom                              Increases INT by 15%.
1       All-Rounder             Increases ATK, DEF, INT and SPD by 5%.
2           Analyze                      Increases scan values by 10%.
3  Animal Colosseum         Increases damage from Earth skills by 15%.
4      Aus Generics  Increases SPD and EVA by 25% when HP drops bel...

In [10]:
digimonlist.head()

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
0,1,Kuramon,Baby,Free,Neutral,2,0,590,77,79,69,68,95
1,2,Pabumon,Baby,Free,Neutral,2,0,950,62,76,76,69,68
2,3,Punimon,Baby,Free,Neutral,2,0,870,50,97,87,50,75
3,4,Botamon,Baby,Free,Neutral,2,0,690,68,77,95,76,61
4,5,Poyomon,Baby,Free,Neutral,2,0,540,98,54,59,95,86